const aiService = require('../services/aiService');
const Quiz = require('../models/Quiz');
const QuizResult = require('../models/QuizResult');
const Assignment = require('../models/Assignment');
const AssignmentSubmission = require('../models/AssignmentSubmission');
const Lesson = require('../models/Lesson');
const catchAsync = require('../utils/catchAsync');
const AppError = require('../utils/AppError');

exports.generateQuiz = catchAsync(async (req, res) => {
  const { topic, difficulty, count, type, content, timeLimit, course, lesson } = req.body;
  if (!topic && !content) throw new AppError('Topic or content is required', 400);

  const quiz = await aiService.generateQuiz({
    topic: topic || 'General Knowledge',
    difficulty: difficulty || 'intermediate',
    count: Math.min(count || 5, 20),
    type: type || 'mcq',
    content: content || '',
    timeLimit: timeLimit || 30,
  });

  res.status(200).json({ success: true, data: quiz, message: 'Quiz generated by AI' });
});

exports.saveGeneratedQuiz = catchAsync(async (req, res) => {
  const { generatedData, course, module, lesson } = req.body;
  if (!generatedData?.questions?.length) throw new AppError('No questions to save', 400);

  const quiz = await Quiz.create({
    title: generatedData.title || 'AI Generated Quiz',
    description: generatedData.description || '',
    course: course || req.body.course,
    module: module || null,
    lesson: lesson || null,
    mentor: req.userId,
    createdBy: req.userId,
    questions: generatedData.questions.map((q) => ({
      question: q.question,
      type: q.options?.length > 0 ? (q.type === 'multiple_select' ? 'multiple_select' : 'mcq') : 'short_answer',
      options: q.options || [],
      correctAnswer: q.correctAnswer || '',
      explanation: q.explanation || '',
      points: q.points || 5,
    })),
    timeLimit: req.body.timeLimit || 30,
    passingScore: req.body.passingScore || 40,
    totalPoints: generatedData.totalPoints || generatedData.questions.reduce((s, q) => s + (q.points || 5), 0),
    isPublished: true,
  });

  res.status(201).json({ success: true, data: quiz, message: 'AI quiz saved successfully' });
});

exports.generateAdaptiveQuiz = catchAsync(async (req, res) => {
  const { topic, count } = req.body;

  // Get student's weak areas from past quiz results
  const pastResults = await QuizResult.find({ student: req.userId, status: 'completed' })
    .populate('quiz', 'title')
    .sort('-createdAt')
    .limit(10);

  const weakTopics = [];
  const performanceByTopic = {};

  pastResults.forEach((r) => {
    const topicName = r.quiz?.title?.split(' ')[0] || 'General';
    if (!performanceByTopic[topicName]) performanceByTopic[topicName] = { total: 0, earned: 0 };
    performanceByTopic[topicName].total += r.totalPoints;
    performanceByTopic[topicName].earned += r.earnedPoints;
  });

  Object.entries(performanceByTopic).forEach(([t, p]) => {
    const pct = p.total > 0 ? (p.earned / p.total) * 100 : 0;
    if (pct < 60) weakTopics.push(t);
  });

  const quiz = await aiService.generateAdaptiveQuiz({
    topic: topic || 'General',
    difficulty: 'intermediate',
    count: Math.min(count || 5, 20),
    previousResults: {
      weakTopics,
      averageScore: pastResults.length > 0
        ? pastResults.reduce((s, r) => s + (r.percentage || 0), 0) / pastResults.length
        : 0,
    },
  });

  res.status(200).json({
    success: true,
    data: { ...quiz, adaptive: true, weakTopics },
    message: weakTopics.length > 0 ? `Adaptive quiz generated focusing on: ${weakTopics.join(', ')}` : 'Adaptive quiz ready',
  });
});

exports.evaluateAssignment = catchAsync(async (req, res) => {
  const { submissionId } = req.params;
  const submission = await AssignmentSubmission.findById(submissionId)
    .populate('assignment', 'title totalPoints rubric')
    .populate('student', 'name email');

  if (!submission) throw new AppError('Submission not found', 404);

  const assignment = submission.assignment;
  const fileText = req.body.fileText || '';
  const submissionText = submission.textSubmission || '';

  const evaluation = await aiService.evaluateAssignment({
    submissionText,
    fileText,
    assignmentTitle: assignment?.title || '',
    rubric: assignment?.rubric || [],
    maxPoints: assignment?.totalPoints || 100,
  });

  const maxScore = assignment?.totalPoints || 100;
  const pct = maxScore > 0 ? (evaluation.score / maxScore) * 100 : 0;
  const letterGrade = pct >= 90 ? 'A' : pct >= 80 ? 'B' : pct >= 70 ? 'C' : pct >= 60 ? 'D' : 'F';

  submission.score = evaluation.score;
  submission.maxScore = maxScore;
  submission.percentage = Math.round(pct);
  submission.grade = letterGrade;
  submission.feedback = evaluation.feedback || '';
  submission.aiFeedback = JSON.stringify({
    strengths: evaluation.strengths,
    improvements: evaluation.improvements,
    weakAreas: evaluation.weakAreas,
    mentorRecommendation: evaluation.mentorRecommendation,
  });
  submission.gradedBy = req.userId;
  submission.gradedAt = new Date();
  submission.status = 'graded';
  await submission.save();

  res.status(200).json({
    success: true,
    data: submission,
    message: 'Assignment evaluated by AI',
  });
});

exports.generateExplanation = catchAsync(async (req, res) => {
  const { question, correctAnswer, userAnswer, context } = req.body;
  if (!question || !correctAnswer) throw new AppError('Question and correct answer required', 400);

  const explanation = await aiService.generateExplanation({ question, correctAnswer, userAnswer, context });
  res.status(200).json({ success: true, data: explanation });
});

exports.generateRevisionQuiz = catchAsync(async (req, res) => {
  const { topic, weakTopics, count } = req.body;

  const quiz = await aiService.generateRevisionQuiz({
    topic: topic || 'General',
    weakTopics: weakTopics || [],
    count: Math.min(count || 5, 20),
  });

  res.status(200).json({ success: true, data: quiz, message: 'Revision quiz generated' });
});

exports.getWeakTopics = catchAsync(async (req, res) => {
  const results = await QuizResult.find({ student: req.userId, status: 'completed' })
    .populate('quiz', 'title')
    .sort('-createdAt');

  const topicPerformance = {};
  results.forEach((r) => {
    const t = r.quiz?.title?.split(' ')[0] || 'General';
    if (!topicPerformance[t]) topicPerformance[t] = { total: 0, earned: 0, attempts: 0 };
    topicPerformance[t].total += r.totalPoints;
    topicPerformance[t].earned += r.earnedPoints;
    topicPerformance[t].attempts += 1;
  });

  const weakTopics = Object.entries(topicPerformance)
    .map(([topic, perf]) => ({
      topic,
      score: perf.total > 0 ? Math.round((perf.earned / perf.total) * 100) : 0,
      attempts: perf.attempts,
      isWeak: perf.total > 0 ? (perf.earned / perf.total) * 100 < 60 : true,
    }))
    .sort((a, b) => a.score - b.score);

  res.status(200).json({ success: true, data: weakTopics });
});

exports.generateFromLesson = catchAsync(async (req, res) => {
  const { lessonId, difficulty, count, type } = req.body;
  const lesson = await Lesson.findById(lessonId);
  if (!lesson) throw new AppError('Lesson not found', 404);

  const content = [lesson.title, lesson.description, lesson.content?.textContent || ''].filter(Boolean).join('\n');

  const quiz = await aiService.generateQuiz({
    topic: lesson.title,
    difficulty: difficulty || 'intermediate',
    count: Math.min(count || 5, 20),
    type: type || 'mcq',
    content,
    timeLimit: 15,
  });

  res.status(200).json({
    success: true,
    data: { ...quiz, lessonId, source: 'lesson' },
    message: 'Quiz generated from lesson content',
  });
});

exports.askDoubt = catchAsync(async (req, res) => {
  const { question, topic, context, courseName } = req.body;
  if (!question) throw new AppError('Question is required', 400);

  const result = await aiService.askDoubt({
    question,
    topic: topic || '',
    context: context || '',
    courseName: courseName || '',
  });

  res.status(200).json({
    success: true,
    data: result,
    message: 'Doubt answered by AI',
  });
});
